name       : haskell-cabal-syntax
version    : 3.6.0.0
release    : 1
source     :
    - https://hackage.haskell.org/package/Cabal-syntax-3.6.0.0/Cabal-syntax-3.6.0.0.tar.gz : ca25e5fc601397565fa857f1aa477740fac7f43d659e77c4d9b1485dca239251
license    : BSD-3-Clause
component  : programming.haskell
summary    : Tools for reading and manipulating the .cabal file format
description: |
    The Cabal-syntax package defines the syntax of the .cabal file format and provides tools for parsing .cabal files.
builddeps  :
    - ghc-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
